version: '3.8'

services:
  database:
    container_name: recipes_database
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recipes
      MYSQL_USER: recipes
      MYSQL_PASSWORD: password
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  nginx:
    container_name: recipes_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ..:/var/www/recipes
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    container_name: recipes_php
    build:
      context: php
    volumes:
      - ..:/var/www/recipes

  adminer:
    container_name: recipes_adminer
    image: adminer
    ports:
      - 666:8080