name: deploy
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
  
jobs:
  tests:
    name: Run tests
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Build Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.1
          php_extensions: gd
      - run: echo "Composer dependencies have been installed"
      - run: composer phpstan
      - run: composer cs

  deploy:
    name: Deploy
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && composer install && php bin/console cache:clear && php bin/console cache:warmup && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
